-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Moves" add column "times_played" integer
--  not null default '0';
