-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."BoardStates" add column "draws" integer
--  not null default '0';
